#!/bin/sh

pgrep_kill()
{
    kill $(ps aux | grep $1 | grep -v grep | awk '{print $2}')
}

kill_sim()
{
    pgrep_kill 'acabslrouter.py'
    pgrep_kill 'acabsimulator.py'
    pgrep_kill 'audioserver.py'

    exit
}

# Catch Ctrl+C
trap kill_sim INT

# Start simulator
./acabsimulator.py "Wall 0" 4001 &
#./acabsimulator.py "Wall 1" 4002 &

# Start server for simulation
./server/acabslrouter.py simulation &

# Start audio server
./audio/audioserver.py &

# Wait
echo press enter to stop the simulation
read dummy

# Clean up
kill_sim
