#!/usr/bin/python

from acabsl import send
import time
import sys
t = .3
x = int(sys.argv[1])
y = int(sys.argv[2])


while 1:
    send(0,x,y,255,0)
    time.sleep(t)
    send(0, x,y,0,255)
    time.sleep(t)
    send(0, x,y,0,0,255)
    time.sleep(t)
    send(0, x,y,0,0,0)
    time.sleep(t)


